version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3020:3000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    networks:
      - local
    command: ["docker/app/start.sh"]

volumes:
    data-volume:

networks:
  local:
